apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: pihole
  namespace: dns
  annotations:
    fluxcd.io/automated: "true"
spec:
  releaseName: pihole
  resetValues: true
  chart:
    repository: https://mojo2600.github.io/pihole-kubernetes/
    name: pihole
    version: 1.7.17
    forceUpgrade: false
  values:
    DNS1: 10.96.0.10
    #DNS2: 1.0.0.2
    persistentVolumeClaim:
      enabled: true
      storageClass: rook-ceph-block
    serviceTCP:
      loadBalancerIP: 192.168.1.12
      annotations:
        metallb.universe.tf/allow-shared-ip: pihole-svc
      type: LoadBalancer
    serviceUDP:
      loadBalancerIP: 192.168.1.12
      annotations:
        metallb.universe.tf/allow-shared-ip: pihole-svc
      type: LoadBalancer
    probes:
      # probes.liveness -- Configure the healthcheck for the ingress controller
      liveness:
        enabled: true
        initialDelaySeconds: 60
        failureThreshold: 10
        timeoutSeconds: 5
      readiness:
        enabled: true
        initialDelaySeconds: 60
        failureThreshold: 480
        timeoutSeconds: 5
