apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: loki
  namespace: logging
  annotations:
    fluxcd.io/automated: "true"
spec:
  releaseName: loki
  resetValues: true
  chart:
    repository: https://grafana.github.io/loki/charts
    name: loki
    version: 0.31.1
    forceUpgrade: false
  values:
    serviceMonitor:
      enabled: true
      additionalLabels:
        release: "prometheus"
    persistence:
      storageClassName: rook-ceph-block
      enabled: true
      accessModes:
      - ReadWriteOnce
      size: 40Gi
    config:
      auth_enabled: false
      server:
        http_listen_port: 3100
      schema_config:
        configs:
        - from: "2018-04-15"
          index:
            period: 168h
            prefix: index_
          object_store: s3
          schema: v9
          store: boltdb
      storage_config:
        aws:
          s3: s3://CWQZ6TR4GYSV50CVDZDZ:BCdDuxZNtU35UUrtYGCFkF8hyi8IkKPDEGc9xxDp@rook-ceph-rgw-my-store.rook-ceph.svc/loki-9e31d7a4-d566-4095-9ea6-c614d2d0c3d2
          s3forcepathstyle: true
          endpoint: rook-ceph-rgw-my-store.rook-ceph.svc
          region: us-east-1
          access_key_id: CWQZ6TR4GYSV50CVDZDZ
          secret_access_key: BCdDuxZNtU35UUrtYGCFkF8hyi8IkKPDEGc9xxDp
          insecure: true
          sse_encryption: false
          http_config:
            idle_conn_timeout: 90s
            response_header_timeout: 0s
            insecure_skip_verify: true
          s3forcepathstyle: true
      chunk_store_config:
        max_look_back_period: 0s
      table_manager:
        retention_deletes_enabled: false
        retention_period: 0s