apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns
  namespace: kube-system
data:
  Corefile: |
    .:53 {
        errors
        health {
           lameduck 5s
        }
        ready
        kubernetes home-server-1.local in-addr.arpa ip6.arpa {
           pods insecure
           fallthrough in-addr.arpa ip6.arpa
           ttl 30
        }
        prometheus :9153
        forward . tls://1.1.1.2 tls://1.0.0.2 {
            tls_servername tls.cloudflare-dns.com
            health_check 5s
        }
        cache 30
        loop
        reload
        loadbalance
    }
